### ISSUE TITLE
[Mobile] Problème de défilement

### ISSUE THREAD

**Issue by SebouChu** [juliendargelos/BetterSched2#10]
Impossibilité de faire défiler la page depuis la zone rouge et donc impossibilité de changer le jour de la semaine

Appareil : LG Nexus 5 (sous Android Marshmallow 6.0.1)
![screenshot_20160920-210531](https://cloud.githubusercontent.com/assets/7761386/18685069/dc57ff02-7f76-11e6-81a3-56512506c5a6.png)

**Comment by juliendargelos** [comment]
## **Pistes**
- **Sans aucun doute un problème avec le preventDefault qui assure le défilement horizontal des jours**: à tester sur la plateforme concernée.

**Comment by juliendargelos** [comment]
Le problème devrait être résolu (f01a99fc42245922f6691b4c9d777972b1e448ee). Tu peux tester et confirmer ?

**Comment by SebouChu** [comment]
Confirmé, problème résolu ! Seulement, le défilement de gauche à droite est un peu dur, j'essaierai de te montrer si on se croise à l'IUT

**Comment by juliendargelos** [comment]
Très bien, je ferme cette issue. J'en rouvrirai une autre pour le problème que tu décris.
