### ISSUE TITLE
[Mobile] Raccourci écran d'accueil

### ISSUE THREAD

**Issue by SebouChu** [juliendargelos/BetterSched2#11]
Le raccourci vers la beta de BetterSched sur l'écran d'accueil mène à une page blanche, même après de multiples tentatives. (Ce problème ne touche pas la version stable de BetterSched)

Appareil : LG Nexus 5 (sous Android Marshmallow 6.0.1)

**Comment by juliendargelos** [comment]
Le "raccourci", c'est le nom de l'application dans la partie gauche de la barre supérieure ?
Si c'est le cas, je n'arrive pas à reproduire le bug avec une configuration similaire.

**Comment by SebouChu** [comment]
Non, quand sur Chrome Android, je fais un raccourci avec "Ajouter à l'écran d'accueil" pour avoir l'icône BetterSched' sur l'écran d'accueil du téléphone

**Comment by juliendargelos** [comment]
D'accord, je vais tester ça alors.

**Comment by juliendargelos** [comment]
En effet, Android recherche automatiquement la page `/index.php` sur les applications web standalone. J'ai ajouté une redirection 301 pour régler ça (67f25ab0b825f058167aad8e230f19056c29a6ac).
