### ISSUE TITLE
[Tablette] Formulaire des paramètres de l'emploi du temps

### ISSUE THREAD

**Issue by SebouChu** [juliendargelos/BetterSched2#12]
Impossibilité de modifier les paramètres de l'emploi du temps. Le clic fait effet sur le défilement des jours.

Appareil : iPad mini 2 (sous iOS 10.0.1)

**Comment by juliendargelos** [comment]
Impossible de reproduire le bug.
Tu m'avais dit que cela semblait fonctionner en fin de compte, c'est toujours le cas ?

**Comment by SebouChu** [comment]
Le bug est résolu depuis aujourd'hui oui !

**Comment by juliendargelos** [comment]
Parfait
