### ISSUE TITLE
Problème de session (ou cookies ?)

### ISSUE THREAD

**Issue by SebouChu** [juliendargelos/BetterSched2#14]
Après avoir changé les paramètres de l'emploi du temps (exemple : MMI S1, Semaine 40, TD 1, TP 2, LV2 Espagnol), si on actualise la page, les paramètres ne sont pas conservées

**Comment by juliendargelos** [comment]
Problème résolu (4028d96d75756d4491c44a9ea96e9cee2794ce7b)
