### ISSUE TITLE
[Mobile] Problème d'affichage

### ISSUE THREAD

**Issue by SebouChu** [juliendargelos/BetterSched2#16]
Petit problème d'affichage au niveau du mardi
Paramètres : semaine 41, MMI S1, TD1, TP2
Voir le bug d'affichage ici (et les changements de params) : https://twitter.com/SebouChu/status/784480793041203200

Appareil : LG Nexus 5 (sous Android Marshmallow 6.0.1)

**Comment by juliendargelos** [comment]
Ajouter un calcul de position pour les premiers blocs de cours **après** filtrage.

**Comment by juliendargelos** [comment]
(@SebouChu on peut poster des images dans les issues github)

**Comment by SebouChu** [comment]
Sur mobile, je peux pas upload d'image c'est pour ça x)

**Comment by juliendargelos** [comment]
Problème résolu (4028d96d75756d4491c44a9ea96e9cee2794ce7b)
