### ISSUE TITLE
Décallage des dates

### ISSUE THREAD

**Issue by treyssatvincent** [juliendargelos/BetterSched2#19]
Les dates dans #sched-week sont décalées (voir screenshoot).
![issue](https://cloud.githubusercontent.com/assets/18269685/22883892/8beabd18-f1f2-11e6-9ac8-519cf0fd2851.jpg)

**Comment by juliendargelos** [comment]
Problème connu, il sera résolu dès que possible.

**Comment by juliendargelos** [comment]
Problème résolu (facd61ac62bfc6839eecf623005bb02a64cbae1a)
