### ISSUE TITLE
Installation et run

### ISSUE THREAD

**Issue by Drazozo** [juliendargelos/BetterSched2#20]
Bonjour, 

A ce jour, je ne parviens pas à lancer le programme sur mon pc et c'est réellement dommage. Sa à l'air d'être un super travail. 

Au plaisir

**Comment by juliendargelos** [comment]
Bonjour,
cette application récupérait des données depuis la solutions Satellys qui n'est désormais plus utilisée à l'IUT Bordeaux Montaigne. Il est toujours possible de récupérer une partie du code front pour de l'affichage d'emploi du temps mais le cœur de l'API n'est plus fonctionnel.

**Comment by Drazozo** [comment]
Ah d'accord, dommage. Merci quand même 😄
