### ISSUE TITLE
[Mobile] Formulaire des paramètres de l'emploi du temps

### ISSUE THREAD

**Issue by SebouChu** [juliendargelos/BetterSched2#9]
Impossibilité de cliquer sur les options (ex : Filière, Année, Semaine...) sur mobile

Appareil : LG Nexus 5 (sous Android Marshmallow 6.0.1)

**Comment by juliendargelos** [comment]
## **Pistes:**
- **Les différents preventDefault répartis sur les évènements touch**: Tests avec désactivation de JS
- **Le bug déjà constaté sur iOS et Mac OS**: La relation for/id ne semble pas être interprétée par webkit. À tester sur d'autres moteurs d'exécution.

**Comment by juliendargelos** [comment]
Le problème est-il toujours présent ?

**Comment by SebouChu** [comment]
Non, il a disparu sur tous mes appareils !
